// import APP_ICONS from '../constants/icons';
// This file contains mock data representing useful or official links,
// primarily associated with KMUTT and other popular platforms.

// Each object in the array represents a single link entry with metadata.
export const dummyData = [
  {
    iconLink:
      'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSMEonWCKdNWyW8tTji8fAJ2rOKRq2kFbkjJYtV3fBLIoD154i--dpCYmv4vziO5IDyhri1',
    linkName: 'KMUTT Official Website',
    playlists: [
      'University',
      'Academics',
      'Events',
      'Haha',
      'Hehe',
      'Hoo',
      'Hee',
    ],
    link: 'https://www.kmutt.ac.th',
    tags: ['#education', '#thailand', '#university'],
    createdAt: new Date('2023-05-15T09:30:00Z'),
  },
  {
    iconLink:
      'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSMEonWCKdNWyW8tTji8fAJ2rOKRq2kFbkjJYtV3fBLIoD154i--dpCYmv4vziO5IDyhri1',
    linkName: 'Computer Science Department',
    playlists: ['CS101', 'Programming', 'Algorithms'],
    link: 'https://cs.kmutt.ac.th',
    tags: ['#computer-science', '#programming', '#bangkok'],
    createdAt: new Date('2023-06-20T14:15:00Z'),
  },
  {
    iconLink:
      'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSMEonWCKdNWyW8tTji8fAJ2rOKRq2kFbkjJYtV3fBLIoD154i--dpCYmv4vziO5IDyhri1',
    linkName: 'KMUTT Library Portal',
    playlists: ['Research Papers', 'E-Books', 'Theses'],
    link: 'https://library.kmutt.ac.th',
    tags: ['#library', '#research', '#resources'],
    createdAt: new Date('2023-07-10T11:00:00Z'),
  },
  {
    iconLink: 'https://cdn-icons-png.flaticon.com/512/25/25231.png',
    linkName: 'KMUTT GitHub',
    playlists: ['Projects', 'Code Samples', 'Open Source'],
    link: 'https://github.kmutt.ac.th',
    tags: ['#development', '#coding', '#version-control'],
    createdAt: new Date('2023-08-05T16:45:00Z'),
  },
  {
    iconLink:
      'https://static.vecteezy.com/system/resources/previews/018/930/572/non_2x/youtube-logo-youtube-icon-transparent-free-png.png',
    linkName: 'KMUTT YouTube',
    playlists: ['Lectures', 'Events', 'Tutorials'],
    link: 'https://youtube.com/kmuttofficial',
    tags: ['#videos', '#learning', '#media'],
    createdAt: new Date('2023-09-12T10:20:00Z'),
  },
  {
    iconLink:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Telegram_logo.svg/2048px-Telegram_logo.svg.png',
    linkName: 'KMUTT Telegram',
    playlists: ['Announcements', 'Student Groups', 'Clubs'],
    link: 'https://t.me/kmuttofficial',
    tags: ['#messaging', '#communication', '#social'],
    createdAt: new Date('2023-10-18T13:10:00Z'),
  },
  {
    iconLink:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Instagram_logo_2016.svg/2048px-Instagram_logo_2016.svg.png',
    linkName: 'KMUTT Instagram',
    playlists: ['Photos', 'Events', 'Student Life'],
    link: 'https://instagram.com/kmuttofficial',
    tags: ['#photos', '#social-media', '#campus'],
    createdAt: new Date('2023-11-22T08:45:00Z'),
  },
  {
    iconLink:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Twitter_new_X_logo.png/1200px-Twitter_new_X_logo.png',
    linkName: 'KMUTT Twitter',
    playlists: ['News', 'Updates', 'Alerts'],
    link: 'https://twitter.com/kmuttofficial',
    tags: ['#microblogging', '#news', '#updates'],
    createdAt: new Date('2023-12-05T12:30:00Z'),
  },
  {
    iconLink:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Facebook_Logo_%282015%29.svg/2048px-Facebook_Logo_%282015%29.svg.png',
    linkName: 'KMUTT Facebook',
    playlists: ['Community', 'Events', 'Alumni'],
    link: 'https://facebook.com/kmuttofficial',
    tags: ['#social', '#networking', '#community'],
    createdAt: new Date('2024-01-15T09:15:00Z'),
  },
  {
    iconLink: 'https://cdn-icons-png.flaticon.com/512/174/174857.png',
    linkName: 'KMUTT LinkedIn',
    playlists: ['Careers', 'Alumni', 'Networking'],
    link: 'https://linkedin.com/school/kmuttofficial',
    tags: ['#professional', '#careers', '#jobs'],
    createdAt: new Date('2024-02-20T14:50:00Z'),
  },
  {
    iconLink:
      'https://static.vecteezy.com/system/resources/previews/022/484/516/original/google-meet-logo-transparent-free-png.png',
    linkName: 'KMUTT Meet',
    playlists: ['Online Classes', 'Meetings', 'Webinars'],
    link: 'https://meet.google.com/kmut',
    tags: ['#video-calls', '#conferencing', '#online'],
    createdAt: new Date('2024-03-10T11:25:00Z'),
  },
  {
    iconLink:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Microsoft_Office_logo_%282013%E2%80%932019%29.svg/2086px-Microsoft_Office_logo_%282013%E2%80%932019%29.svg.png',
    linkName: 'KMUTT Office 365',
    playlists: ['Documents', 'Email', 'Calendar'],
    link: 'https://office.kmutt.ac.th',
    tags: ['#productivity', '#email', '#tools'],
    createdAt: new Date('2024-04-05T16:10:00Z'),
  },
  {
    iconLink: 'https://cdn-icons-png.flaticon.com/512/2965/2965300.png',
    linkName: 'KMUTT Moodle',
    playlists: ['Courses', 'Assignments', 'Quizzes'],
    link: 'https://moodle.kmutt.ac.th',
    tags: ['#lms', '#elearning', '#education'],
    createdAt: new Date('2024-05-12T08:40:00Z'),
  },
  {
    iconLink: 'https://cdn-icons-png.flaticon.com/512/888/888882.png',
    linkName: 'KMUTT Research Portal',
    playlists: ['Publications', 'Projects', 'Conferences'],
    link: 'https://research.kmutt.ac.th',
    tags: ['#academic', '#science', '#innovation'],
    createdAt: new Date('2024-06-18T13:55:00Z'),
  },
  {
    iconLink: 'https://cdn-icons-png.flaticon.com/512/3059/3059518.png',
    linkName: 'KMUTT Job Board',
    playlists: ['Internships', 'Full-time', 'Part-time'],
    link: 'https://careers.kmutt.ac.th',
    tags: ['#employment', '#opportunities', '#recruitment'],
    createdAt: new Date('2024-07-22T10:05:00Z'),
  },
  {
    iconLink: 'https://cdn-icons-png.flaticon.com/512/3059/3059539.png',
    linkName: 'KMUTT Alumni',
    playlists: ['Network', 'Events', 'Donations'],
    link: 'https://alumni.kmutt.ac.th',
    tags: ['#graduates', '#community', '#support'],
    createdAt: new Date('2024-08-30T15:20:00Z'),
  },
  {
    iconLink: 'https://cdn-icons-png.flaticon.com/512/3059/3059529.png',
    linkName: 'KMUTT Sports',
    playlists: ['Schedule', 'Teams', 'Facilities'],
    link: 'https://sports.kmutt.ac.th',
    tags: ['#athletics', '#fitness', '#recreation'],
    createdAt: new Date('2024-09-14T09:35:00Z'),
  },
  {
    iconLink: 'https://cdn-icons-png.flaticon.com/512/3059/3059504.png',
    linkName: 'KMUTT Health Center',
    playlists: ['Services', 'Appointments', 'Wellness'],
    link: 'https://health.kmutt.ac.th',
    tags: ['#medical', '#wellbeing', '#counseling'],
    createdAt: new Date('2024-10-05T14:10:00Z'),
  },
  {
    iconLink: 'https://cdn-icons-png.flaticon.com/512/3059/3059474.png',
    linkName: 'KMUTT Housing',
    playlists: ['Dormitories', 'Off-campus', 'Applications'],
    link: 'https://housing.kmutt.ac.th',
    tags: ['#accommodation', '#living', '#residence'],
    createdAt: new Date('2024-11-11T11:45:00Z'),
  },
  {
    iconLink: 'https://cdn-icons-png.flaticon.com/512/3059/3059497.png',
    linkName: 'KMUTT Transportation',
    playlists: ['Shuttle', 'Parking', 'Maps'],
    link: 'https://transport.kmutt.ac.th',
    tags: ['#commute', '#travel', '#logistics'],
    createdAt: new Date('2024-12-20T08:15:00Z'),
  },
  {
    iconLink: 'https://cdn-icons-png.flaticon.com/512/174/174857.png',
    linkName: 'Google Search',
    playlists: ['Search', 'Web', 'Utility'],
    link: 'https://www.google.com',
    tags: ['#search', '#technology', '#web'],
    createdAt: new Date('2023-04-10T08:00:00Z'),
  },
  {
    iconLink: 'https://cdn-icons-png.flaticon.com/512/732/732221.png',
    linkName: 'Gmail',
    playlists: ['Email', 'Communication'],
    link: 'https://mail.google.com',
    tags: ['#email', '#communication', '#google'],
    createdAt: new Date('2023-04-15T11:45:00Z'),
  },
  {
    iconLink: 'https://cdn-icons-png.flaticon.com/512/174/174872.png',
    linkName: 'YouTube',
    playlists: ['Entertainment', 'Music', 'Tutorials'],
    link: 'https://www.youtube.com',
    tags: ['#video', '#streaming', '#media'],
    createdAt: new Date('2023-04-20T10:10:00Z'),
  },
  {
    iconLink: 'https://cdn-icons-png.flaticon.com/512/145/145802.png',
    linkName: 'Facebook',
    playlists: ['Friends', 'Groups', 'Marketplace'],
    link: 'https://www.facebook.com',
    tags: ['#social', '#friends', '#community'],
    createdAt: new Date('2023-04-25T14:30:00Z'),
  },
  {
    iconLink: 'https://cdn-icons-png.flaticon.com/512/174/174881.png',
    linkName: 'Instagram',
    playlists: ['Photos', 'Stories', 'Reels'],
    link: 'https://www.instagram.com',
    tags: ['#photos', '#socialmedia', '#lifestyle'],
    createdAt: new Date('2023-05-01T09:00:00Z'),
  },
  {
    iconLink: 'https://cdn-icons-png.flaticon.com/512/733/733579.png',
    linkName: 'LinkedIn',
    playlists: ['Jobs', 'Networking', 'Professional'],
    link: 'https://www.linkedin.com',
    tags: ['#jobs', '#networking', '#career'],
    createdAt: new Date('2023-05-05T15:20:00Z'),
  },
  {
    iconLink: 'https://cdn-icons-png.flaticon.com/512/733/733635.png',
    linkName: 'Twitter (X)',
    playlists: ['Trending', 'News', 'Tweets'],
    link: 'https://twitter.com',
    tags: ['#microblogging', '#socialmedia', '#updates'],
    createdAt: new Date('2023-05-10T17:45:00Z'),
  },
  {
    iconLink: 'https://cdn-icons-png.flaticon.com/512/25/25231.png',
    linkName: 'GitHub',
    playlists: ['Repositories', 'Open Source', 'Development'],
    link: 'https://github.com',
    tags: ['#code', '#opensource', '#versioncontrol'],
    createdAt: new Date('2023-05-15T08:20:00Z'),
  },
  {
    iconLink: 'https://cdn-icons-png.flaticon.com/512/5968/5968764.png',
    linkName: 'Reddit',
    playlists: ['Communities', 'Discussions', 'Memes'],
    link: 'https://www.reddit.com',
    tags: ['#forums', '#trending', '#discussions'],
    createdAt: new Date('2023-05-20T10:00:00Z'),
  },
  {
    iconLink: 'https://cdn-icons-png.flaticon.com/512/174/174844.png',
    linkName: 'Netflix',
    playlists: ['Movies', 'TV Shows', 'Originals'],
    link: 'https://www.netflix.com',
    tags: ['#streaming', '#entertainment', '#movies'],
    createdAt: new Date('2023-05-25T20:00:00Z'),
  },
  {
    iconLink: 'https://cdn-icons-png.flaticon.com/512/732/732228.png',
    linkName: 'Yahoo Mail',
    playlists: ['Inbox', 'News', 'Finance'],
    link: 'https://mail.yahoo.com',
    tags: ['#email', '#news', '#yahoo'],
    createdAt: new Date('2023-06-01T09:10:00Z'),
  },
  {
    iconLink: 'https://cdn-icons-png.flaticon.com/512/5968/5968705.png',
    linkName: 'Amazon',
    playlists: ['Shopping', 'Deals', 'Tech'],
    link: 'https://www.amazon.com',
    tags: ['#ecommerce', '#shopping', '#tech'],
    createdAt: new Date('2023-06-08T13:30:00Z'),
  },
  {
    iconLink: 'https://cdn-icons-png.flaticon.com/512/732/732200.png',
    linkName: 'Microsoft',
    playlists: ['Office', 'Cloud', 'Windows'],
    link: 'https://www.microsoft.com',
    tags: ['#software', '#windows', '#cloud'],
    createdAt: new Date('2023-06-12T12:45:00Z'),
  },
  {
    iconLink: 'https://cdn-icons-png.flaticon.com/512/270/270798.png',
    linkName: 'Dropbox',
    playlists: ['Files', 'Backup', 'Cloud Storage'],
    link: 'https://www.dropbox.com',
    tags: ['#cloud', '#storage', '#files'],
    createdAt: new Date('2023-06-15T08:50:00Z'),
  },
  {
    iconLink: 'https://cdn-icons-png.flaticon.com/512/2111/2111646.png',
    linkName: 'TikTok',
    playlists: ['Shorts', 'Dance', 'Viral'],
    link: 'https://www.tiktok.com',
    tags: ['#videos', '#fun', '#viral'],
    createdAt: new Date('2023-06-18T17:05:00Z'),
  },
  {
    iconLink: 'https://cdn-icons-png.flaticon.com/512/2111/2111728.png',
    linkName: 'Pinterest',
    playlists: ['Design', 'Ideas', 'Inspiration'],
    link: 'https://www.pinterest.com',
    tags: ['#images', '#ideas', '#creativity'],
    createdAt: new Date('2023-06-22T11:40:00Z'),
  },
  {
    iconLink: 'https://cdn-icons-png.flaticon.com/512/2111/2111624.png',
    linkName: 'Spotify',
    playlists: ['Music', 'Podcasts', 'Playlists'],
    link: 'https://www.spotify.com',
    tags: ['#music', '#audio', '#entertainment'],
    createdAt: new Date('2023-06-25T10:25:00Z'),
  },
  {
    iconLink: 'https://cdn-icons-png.flaticon.com/512/2111/2111703.png',
    linkName: 'Twitch',
    playlists: ['Gaming', 'Streaming', 'Esports'],
    link: 'https://www.twitch.tv',
    tags: ['#gaming', '#live', '#stream'],
    createdAt: new Date('2023-06-30T16:15:00Z'),
  },
  {
    iconLink: 'https://cdn-icons-png.flaticon.com/512/906/906324.png',
    linkName: 'Coursera',
    playlists: ['Courses', 'Degrees', 'Certificates'],
    link: 'https://www.coursera.org',
    tags: ['#education', '#onlinelearning', '#certification'],
    createdAt: new Date('2023-07-03T14:00:00Z'),
  },
  {
    iconLink: 'https://cdn-icons-png.flaticon.com/512/5968/5968690.png',
    linkName: 'Khan Academy',
    playlists: ['Math', 'Science', 'History'],
    link: 'https://www.khanacademy.org',
    tags: ['#learning', '#free', '#education'],
    createdAt: new Date('2023-07-06T09:35:00Z'),
  },
  
];

export const dummyPlaylist = [
  {
    id: 1,
    name: 'KMUTT Official',
    number: 3,
    iconLink: 'camera',
    description: 'Official university links and resources',
  },
  {
    id: 2,
    name: 'Computer Science',
    number: 13,
    iconLink: 'code',
    description: 'Programming and CS related materials',
  },
  {
    id: 3,
    name: 'Research',
    number: 32,
    iconLink: 'book',
    description: 'Academic papers and research materials',
  },
  {
    id: 4,
    name: 'Social Media',
    number: 31,
    iconLink: 'share',
    description: 'All university social media accounts',
  },
  {
    id: 5,
    name: 'Learning Resources',
    number: 53,
    iconLink: 'graduation-cap',
    description: 'Educational materials and courses',
  },
  {
    id: 6,
    name: 'Student Services',
    number: 43,
    iconLink: 'users',
    description: 'Services available for students',
  },
  {
    id: 7,
    name: 'Events',
    number: 30,
    iconLink: 'calendar',
    description: 'University events and activities',
  },
  {
    id: 8,
    name: 'Career Development',
    number: 25,
    iconLink: 'briefcase',
    description: 'Job opportunities and career resources',
  },
  {
    id: 9,
    name: 'Alumni Network',
    number: 18,
    iconLink: 'network-wired',
    description: 'Alumni connections and resources',
  },
  {
    id: 10,
    name: 'Sports & Recreation',
    number: 12,
    iconLink: 'running',
    description: 'Athletics and recreational activities',
  },
  {
    id: 11,
    name: 'Health & Wellness',
    number: 9,
    iconLink: 'heartbeat',
    description: 'Health services and wellness programs',
  },
  {
    id: 12,
    name: 'Housing',
    number: 7,
    iconLink: 'home',
    description: 'Dormitory and housing information',
  },
  {
    id: 13,
    name: 'Transportation',
    number: 5,
    iconLink: 'bus',
    description: 'Campus transportation options',
  },
  {
    id: 14,
    name: 'Student Organizations',
    number: 22,
    iconLink: 'users-cog',
    description: 'Clubs and student groups',
  },
  {
    id: 15,
    name: 'Library Resources',
    number: 28,
    iconLink: 'book-open',
    description: 'Library materials and databases',
  },
  {
    id: 16,
    name: 'International Programs',
    number: 15,
    iconLink: 'globe',
    description: 'Study abroad and exchange programs',
  },
  {
    id: 17,
    name: 'Financial Aid',
    number: 11,
    iconLink: 'money-bill-wave',
    description: 'Scholarships and financial assistance',
  },
  {
    id: 18,
    name: 'Technology Services',
    number: 19,
    iconLink: 'laptop',
    description: 'IT support and tech resources',
  },
  {
    id: 19,
    name: 'Academic Departments',
    number: 27,
    iconLink: 'university',
    description: 'Links to all academic departments',
  },
  {
    id: 20,
    name: 'Administrative',
    number: 8,
    iconLink: 'clipboard-list',
    description: 'Administrative forms and procedures',
  },
   // The entire array can be used to populate a UI dashboard, 
  // search/filter component, or categorized link manager.
];

export const dummyTags = [
  { id: 1, name: '#education' },
  { id: 2, name: '#university' },
  { id: 3, name: '#thailand' },
  { id: 4, name: '#computer-science' },
  { id: 5, name: '#programming' },
  { id: 6, name: '#research' },
  { id: 7, name: '#library' },
  { id: 8, name: '#social-media' },
  { id: 9, name: '#career' },
  { id: 10, name: '#jobs' },
  { id: 11, name: '#student-life' },
  { id: 12, name: '#events' },
  { id: 13, name: '#health' },
  { id: 14, name: '#wellness' },
  { id: 15, name: '#sports' },
  { id: 16, name: '#housing' },
  { id: 17, name: '#transportation' },
  { id: 18, name: '#technology' },
  { id: 19, name: '#international' },
  { id: 20, name: '#financial-aid' },
];
